name: ZY_Player_flutter
description: 免费影视资源播放

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Localization https://github.com/dart-lang/intl
  intl: ^0.17.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.0.0
  # 网络库 https://github.com/flutterchina/dio
  dio: ^4.0.0
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^2.0.1
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^6.0.3
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.6.0
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^2.0.4
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.4.0
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.3
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.0.0
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^6.0.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: 5.0.0
  # 事件通知
  event_bus: 2.0.0
  #json 序列化
  json_annotation: 4.0.1
  #播放器
  chewie: 1.0.0
  video_player: 2.1.1
  #更新
  ota_update: ^3.0.2
  package_info: ^2.0.0
  flutter_update_dialog: ^2.0.0
  #动画
  flutter_staggered_animations: ^1.0.0
  # 视频推送
  flutter_dlna:
    git:
      url: https://github.com/xiaojia21190/flutter_dlna.git
  #dialog
  giffy_dialog: 1.8.0
  #权限
  permission_handler: 7.1.0
  #二维码
  qr_flutter: 4.0.0
  image_gallery_saver: 1.6.9

  battery: 2.0.1
  animations: ^2.0.0

  flutter_screen: 0.0.2
  just_audio: ^0.7.4+1
  shimmer: 2.0.0

  screen_ratio_adapter: ^1.0.2

  device_info: ^2.0.0

  animated_bottom_navigation_bar: ^0.3.2
  fradio: ^1.0.1

dev_dependencies:
  build_runner: ^2.0.1
  json_serializable: 4.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/login/
    - assets/images/home/
    - assets/images/state/
    - assets/images/book/

  fonts:
    - family: xuifont #指定一个字体名
      fonts:
        - asset: assets/fonts/iconfont.ttf
