name: ZY_Player_flutter
description: 免费影视资源播放

publish_to: 'none'
version_name: 2.7.1

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    # Localization https://github.com/dart-lang/intl
    intl: ^0.17.0
    # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
    oktoast: ^3.2.0
    # 网络库 https://github.com/flutterchina/dio
    dio: ^4.0.4
    # Flutter 常用工具类库 https://github.com/Sky24n/flustars
    flustars_flutter3: ^3.0.0
    # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
    flutter_swiper_null_safety_flutter3: ^2.0.0
    # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
    url_launcher: ^6.0.20
    # 侧滑删除 https://github.com/letsar/flutter_slidable
    flutter_slidable: ^1.2.0
    # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
    webview_flutter: ^3.0.1
    # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
    keyboard_actions: ^4.0.1
    # 路由框架 https://github.com/theyakka/fluro
    fluro: ^2.0.3
    # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
    cached_network_image: ^3.2.0
    # 格式化String https://github.com/Naddiseo/dart-sprintf
    sprintf: ^6.0.0
    # 状态管理 https://github.com/rrousselGit/provider
    provider: ^6.0.1
    # 事件通知
    event_bus: 2.0.0
    #json 序列化
    json_annotation: ^4.4.0
    #播放器
    chewie: ^1.3.1
    video_player: ^2.2.7
    #更新
    ota_update: ^3.1.1
    package_info_plus: ^1.3.0
    flutter_update_dialog: ^2.0.0
    #动画
    flutter_staggered_animations: ^1.0.0
    # 视频推送
    flutter_dlna:
        git:
            url: https://github.com/xiaojia21190/flutter_dlna.git
    #dialog https://github.com/apgapg/giffy_dialog.git
    giffy_dialog: ^1.8.0
    #权限
    permission_handler: 8.2.5
    #二维码
    qr_flutter: ^4.0.0
    image_gallery_saver: ^1.7.1

    battery_plus: ^2.1.3
    animations: ^2.0.3

    flutter_screen_wake: ^1.0.2
    just_audio: ^0.9.20
    shimmer: 2.0.0

    screen_ratio_adapter: ^3.0.0

    device_info_plus: ^3.2.2

    animated_bottom_navigation_bar: ^0.3.2
    fradio_nullsafety: ^2.0.2
    webview_cookie_manager: ^2.0.6

dev_dependencies:
    build_runner: ^2.1.8
    json_serializable: ^6.1.5
    flutter_test:
        sdk: flutter

dependency_overrides:
    platform: ^3.1.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/images/login/
        - assets/images/home/
        - assets/images/state/
        - assets/images/book/

    fonts:
        - family: xuifont #指定一个字体名
          fonts:
              - asset: assets/fonts/iconfont.ttf
